#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'

cookbook 'add-vagrantuser',
   :github => 'lonniev/add-vagrantuser'
   
cookbook 'ubuntu-desktop',
   :github => 'lonniev/ubuntu-desktop'

cookbook 'ubuntu-xfce4',
   :github => 'lonniev/ubuntu-xfce4'

cookbook 'xrdp'

cookbook 'java'

cookbook 'maven'

cookbook 'eclipse',
   :github => 'geocent-cookbooks/eclipse'
